kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
name: case-study
nodes:
  - role: control-plane
    extraPortMappings:
        - containerPort: 443
          hostPort: 443
          protocol: TCP
  - role: worker
  - role: worker