kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
name: case-study
nodes:
  - role: control-plane
    kubeadmConfigPatches:
      - |
        kind: InitConfiguration
        nodeRegistration:
          taints:
            - key: "node-role.kubernetes.io/control-plane"
              effect: "NoSchedule"
  - role: worker
  - role: worker