apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: prod-reader
  namespace: prod
rules:
  - apiGroups: [""]
    resources: ["pods", "services", "configmaps", "secrets"]
    verbs: ["get", "list", "watch"]
