apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: prod-binding
  namespace: prod
subjects:
  - kind: ServiceAccount
    name: prod-user
    namespace: prod
roleRef:
  kind: Role
  name: prod-reader
  apiGroup: rbac.authorization.k8s.io
  