apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: test-binding
  namespace: test
subjects:
  - kind: ServiceAccount
    name: test-user
    namespace: test
roleRef:
  kind: Role
  name: test-reader
  apiGroup: rbac.authorization.k8s.io
  