apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-cm
  namespace: argocd
data:
  policy.default: role:readonly
  policy.csv: |
    p, role:admin, applications, *, */*, allow
    p, role:readonly, applications, get, */*, allow
    g, administrator, role:admin
    g, reader, role:readonly
  accounts.administrator: apiKey, login
  accounts.reader: apiKey, login
  