resources:
  - ../base
  - frontend-ingress.yaml
  - sealed-postgres-dev.yaml
  - rbac/dev-role.yaml
  - rbac/dev-role-binding.yaml
  - rbac/dev-service-account.yaml
  - network-policy.yaml

patches:
  - path: patch-frontend.yaml
    target:
      kind: Deployment
      name: frontend
  - path: patch-backend.yaml
    target:
      kind: Deployment
      name: backend
