apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
spec:
  replicas: 3
  revisionHistoryLimit: 1
  template:
    spec:
      containers:
        - name: frontend
          image: danilgutak/click-frontend:latest
          resources:
            limits:
              cpu: "1000m"
              memory: "512Mi"
            requests:
              cpu: "200m"
              memory: "256Mi"

