apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: click-dev-cert
  namespace: dev
spec:
  secretName: click-dev-tls
  dnsNames:
    - click.dev.local
  issuerRef:
    name: selfsigned-issuer
    kind: ClusterIssuer
