apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: argocd-cert
  namespace: argocd
spec:
  secretName: argocd-tls
  dnsNames:
    - argocd.local
  issuerRef:
    name: selfsigned-issuer
    kind: ClusterIssuer
  commonName: argocd.local